from django.contrib.auth import views as auth_views
from django.urls import include, path

from conference import views

urlpatterns = [
    path("", views.home_view),
    path("dashboard", views.dashboard_view),
    path("dashboard/", views.dashboard_view),
    path("billing", views.billing_dashboard_view),
    path("billing/", views.billing_dashboard_view),
    path("my/meetings/<str:meeting_ref>", views.meeting_room_ref_view),
    path("my/meetings/<str:meeting_ref>/", views.meeting_room_ref_view),
    path("m/<str:share_code>", views.meeting_room_share_view),
    path("m/<str:share_code>/", views.meeting_room_share_view),
    path(
        "accounts/login",
        views.ControlledLoginView.as_view(),
    ),
    path("accounts/logout", auth_views.LogoutView.as_view(next_page="/")),
    path("accounts/register", views.register_page_view),
    path("auth/techcloud/login", views.techcloud_oauth_start),
    path("callback", views.techcloud_oauth_callback),
    path("auth/jwt", views.session_jwt),
    path("auth/logout", views.session_logout),
    path("api/livekit/webhook", views.livekit_webhook),
    path("api/profile", views.my_profile),
    path("api/billing/me", views.billing_me),
    path("api/billing/overview", views.billing_overview),
    path("api/billing/users/export", views.billing_users_export),
    path("api/billing/plans", views.billing_plans),
    path("api/billing/plans/<int:plan_id>", views.billing_plan_detail),
    path("api/billing/users/<int:user_id>/plan", views.billing_user_plan_assign),
    path("api/system/auth-options", views.system_auth_options),
    path("api/system/recording-storage", views.recording_storage_config),
    path("api/recordings", views.recordings),
    path("api/recordings/<int:recording_id>", views.recording_delete),
    path("api/recordings/<int:recording_id>/download", views.recording_download),
    path("meetings/<int:meeting_id>", views.meeting_room_view),
    path("meetings/<int:meeting_id>/", views.meeting_room_view),
    path("api/auth/register", views.register_api),
    path("api/auth/login", views.login_api),
    path("api/meetings", views.meetings),
    path("api/meetings/join", views.join_meeting),
    path("api/meetings/<int:meeting_id>", views.meeting_detail),
    path("api/meetings/<int:meeting_id>/outlook.ics", views.meeting_outlook_ics),
    path("api/meetings/<int:meeting_id>/join-token", views.meeting_join_token),
    path("api/meetings/<int:meeting_id>/my-display-name", views.my_meeting_display_name),
    path("api/meetings/<int:meeting_id>/members", views.meeting_members),
    path("api/meetings/<int:meeting_id>/members/raise-hand", views.meeting_raise_hand),
    path("api/meetings/<int:meeting_id>/messages", views.meeting_messages),
    path("api/meetings/<int:meeting_id>/messages/<int:message_id>", views.meeting_message_recall),
    path("api/meetings/<int:meeting_id>/recordings", views.meeting_recordings),
    path("api/meetings/<int:meeting_id>/recordings/egress", views.meeting_recording_egress_status),
    path("api/meetings/<int:meeting_id>/recordings/egress/start", views.meeting_recording_egress_start),
    path("api/meetings/<int:meeting_id>/recordings/egress/stop", views.meeting_recording_egress_stop),
    path("api/my/meetings/<str:meeting_ref>", views.meeting_detail_ref),
    path("api/my/meetings/<str:meeting_ref>/outlook.ics", views.meeting_outlook_ics_ref),
    path("api/my/meetings/<str:meeting_ref>/join-token", views.meeting_join_token_ref),
    path("api/my/meetings/<str:meeting_ref>/my-display-name", views.my_meeting_display_name_ref),
    path("api/my/meetings/<str:meeting_ref>/members", views.meeting_members_ref),
    path("api/my/meetings/<str:meeting_ref>/members/raise-hand", views.meeting_raise_hand_ref),
    path("api/my/meetings/<str:meeting_ref>/messages", views.meeting_messages_ref),
    path("api/my/meetings/<str:meeting_ref>/messages/<int:message_id>", views.meeting_message_recall_ref),
    path("api/my/meetings/<str:meeting_ref>/recordings", views.meeting_recordings_ref),
    path("api/my/meetings/<str:meeting_ref>/recordings/egress", views.meeting_recording_egress_status_ref),
    path("api/my/meetings/<str:meeting_ref>/recordings/egress/start", views.meeting_recording_egress_start_ref),
    path("api/my/meetings/<str:meeting_ref>/recordings/egress/stop", views.meeting_recording_egress_stop_ref),
    path("api/public/meetings/share/<str:share_code>", views.public_meeting_detail),
    path("api/public/meetings/share/<str:share_code>/members", views.public_meeting_members),
    path("api/public/meetings/share/<str:share_code>/messages", views.public_meeting_messages),
    path("api/public/meetings/share/<str:share_code>/messages/<int:message_id>", views.public_meeting_message_recall),
    path("api/public/meetings/share/<str:share_code>/join-token", views.public_meeting_join_token),
    path("api/orgs/my", views.my_orgs),
    path("api/orgs/<int:org_id>/members", views.org_members),
    path("api/audit/logs", views.audit_logs),
    path("", include("conference.routes.controls")),
]
