from django.urls import path

from conference.api import controls


urlpatterns = [
    path("api/meetings/<int:meeting_id>/controls", controls.meeting_controls),
    path("api/meetings/<int:meeting_id>/members/mute-all", controls.meeting_mute_all),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/role", controls.meeting_member_role),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/mute", controls.meeting_member_mute),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/video", controls.meeting_member_video),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/mic-permission", controls.meeting_member_mic_permission),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/video-permission", controls.meeting_member_video_permission),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/chat-permission", controls.meeting_member_chat_permission),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/screen-share-permission", controls.meeting_member_screen_share_permission),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/display-name", controls.meeting_member_display_name_control),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>/stop-share", controls.meeting_member_stop_share),
    path("api/meetings/<int:meeting_id>/members/<int:target_user_id>", controls.meeting_member_remove),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/mute", controls.meeting_participant_mute),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/video", controls.meeting_participant_video),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/mic-permission", controls.meeting_participant_mic_permission),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/video-permission", controls.meeting_participant_video_permission),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/chat-permission", controls.meeting_participant_chat_permission),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/screen-share-permission", controls.meeting_participant_screen_share_permission),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/display-name", controls.meeting_participant_display_name_control),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>/stop-share", controls.meeting_participant_stop_share),
    path("api/meetings/<int:meeting_id>/participants/<str:participant_identity>", controls.meeting_participant_remove),
    path("api/meetings/<int:meeting_id>/host-leave", controls.meeting_host_leave),
    path("api/meetings/<int:meeting_id>/waiting-room", controls.meeting_waiting_room_entries),
    path("api/meetings/<int:meeting_id>/waiting-room/<int:target_user_id>", controls.meeting_waiting_room_review),
    path("api/meetings/<int:meeting_id>/blocked-members", controls.meeting_blocked_members),
    path("api/meetings/<int:meeting_id>/blocked-members/<int:target_user_id>", controls.meeting_unblock_member),
    path("api/my/meetings/<str:meeting_ref>/controls", controls.meeting_controls_ref),
    path("api/my/meetings/<str:meeting_ref>/members/mute-all", controls.meeting_mute_all_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/role", controls.meeting_member_role_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/mute", controls.meeting_member_mute_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/video", controls.meeting_member_video_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/mic-permission", controls.meeting_member_mic_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/video-permission", controls.meeting_member_video_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/chat-permission", controls.meeting_member_chat_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/screen-share-permission", controls.meeting_member_screen_share_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/display-name", controls.meeting_member_display_name_control_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>/stop-share", controls.meeting_member_stop_share_ref),
    path("api/my/meetings/<str:meeting_ref>/members/<int:target_user_id>", controls.meeting_member_remove_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/mute", controls.meeting_participant_mute_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/video", controls.meeting_participant_video_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/mic-permission", controls.meeting_participant_mic_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/video-permission", controls.meeting_participant_video_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/chat-permission", controls.meeting_participant_chat_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/screen-share-permission", controls.meeting_participant_screen_share_permission_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/display-name", controls.meeting_participant_display_name_control_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>/stop-share", controls.meeting_participant_stop_share_ref),
    path("api/my/meetings/<str:meeting_ref>/participants/<str:participant_identity>", controls.meeting_participant_remove_ref),
    path("api/my/meetings/<str:meeting_ref>/host-leave", controls.meeting_host_leave_ref),
    path("api/my/meetings/<str:meeting_ref>/waiting-room", controls.meeting_waiting_room_entries_ref),
    path("api/my/meetings/<str:meeting_ref>/waiting-room/<int:target_user_id>", controls.meeting_waiting_room_review_ref),
    path("api/my/meetings/<str:meeting_ref>/blocked-members", controls.meeting_blocked_members_ref),
    path("api/my/meetings/<str:meeting_ref>/blocked-members/<int:target_user_id>", controls.meeting_unblock_member_ref),
]
