# Generated by Django 5.2.2 on 2026-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0005_meeting_allow_member_video_meeting_allow_self_unmute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="allow_guest_link_join",
            field=models.BooleanField(default=True),
        ),
    ]
