# Generated by Django 5.2.2 on 2026-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0006_meeting_allow_guest_link_join"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="actual_started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
