# Generated by Django 5.2.2 on 2026-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0007_meeting_actual_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingmember",
            name="allow_chat_override",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingmember",
            name="allow_member_video_override",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingmember",
            name="allow_screen_share_override",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingmember",
            name="allow_self_unmute_override",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingmember",
            name="mic_request_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meetingmember",
            name="video_request_pending",
            field=models.BooleanField(default=False),
        ),
    ]
