# Generated by Django 5.2.2 on 2026-04-02 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_meetingrecording_recordingstorageconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='active_egress_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='active_egress_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='meeting',
            name='active_egress_relative_path',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AddField(
            model_name='meeting',
            name='active_egress_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='active_egress_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_meeting_egress_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='active_egress_storage_root',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='egress_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
