# Generated by Django 5.2.2 on 2026-04-03 12:01

import django.db.models.deletion
from django.db import migrations, models


def backfill_meeting_recording_snapshots(apps, schema_editor):
    MeetingRecording = apps.get_model('conference', 'MeetingRecording')
    for row in MeetingRecording.objects.select_related('meeting').all().iterator():
        meeting = getattr(row, 'meeting', None)
        if meeting is None:
            continue
        changed = False
        if row.meeting_id_snapshot is None:
            row.meeting_id_snapshot = row.meeting_id
            changed = True
        if not row.meeting_title_snapshot:
            row.meeting_title_snapshot = (getattr(meeting, 'title', '') or '').strip()
            changed = True
        if not row.meeting_room_name_snapshot:
            row.meeting_room_name_snapshot = (getattr(meeting, 'room_name', '') or '').strip()
            changed = True
        if changed:
            row.save(
                update_fields=[
                    'meeting_id_snapshot',
                    'meeting_title_snapshot',
                    'meeting_room_name_snapshot',
                ]
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_meeting_active_egress_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='meeting_id_snapshot',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='meeting_room_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='meeting_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(backfill_meeting_recording_snapshots, noop_reverse),
        migrations.AlterField(
            model_name='meetingrecording',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='conference.meeting'),
        ),
    ]
