# Generated by Django 5.2.2 on 2026-04-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_meetingrecording_meeting_id_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmember',
            name='display_name_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MeetingGuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identity', models.CharField(db_index=True, max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('display_name_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_participants', to='conference.meeting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meeting', 'participant_identity'), name='uq_meeting_guest_participant_identity')],
            },
        ),
    ]
