# Generated by Django 5.2.2 on 2026-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0016_systemauthconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_base_url",
            field=models.CharField(
                blank=True,
                default="https://api.openai.com",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_display_name",
            field=models.CharField(blank=True, default="实时语音助手", max_length=80),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_model",
            field=models.CharField(blank=True, default="gpt-realtime", max_length=120),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_voice",
            field=models.CharField(blank=True, default="marin", max_length=40),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="audio_base64",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="audio_mime_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="is_realtime_bot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="sender_display_name_override",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
