# Generated by Django 5.2.2 on 2026-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0017_meeting_realtime_bot_and_message_audio_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("volcengine", "Volcengine")],
                default="openai",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_volc_access_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_volc_app_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_volc_app_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_volc_resource_id",
            field=models.CharField(blank=True, default="volc.speech.dialog", max_length=120),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_volc_uid",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="meeting",
            name="realtime_bot_volc_ws_url",
            field=models.CharField(
                blank=True,
                default="wss://openspeech.bytedance.com/api/v3/realtime/dialogue",
                max_length=255,
            ),
        ),
    ]
