# Generated by Django 5.2.2 on 2026-04-06 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_meeting_realtime_bot_and_message_audio_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS conference_meetingagentmessage;",
                "DROP TABLE IF EXISTS conference_meetingagentsession;",
                "DROP TABLE IF EXISTS conference_meetingtranscriptchunk;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='MeetingAgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('codex', 'Codex'), ('claude', 'Claude')], max_length=16)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('presence_status', models.CharField(choices=[('offline', 'Offline'), ('connecting', 'Connecting'), ('idle', 'Idle'), ('listening', 'Listening'), ('thinking', 'Thinking'), ('working', 'Working'), ('done', 'Done'), ('error', 'Error')], default='offline', max_length=16)),
                ('current_task_title', models.CharField(blank=True, default='', max_length=200)),
                ('current_task_status', models.CharField(blank=True, default='', max_length=40)),
                ('current_context_chunk_ids', models.JSONField(blank=True, default=list)),
                ('latest_short_reply', models.TextField(blank=True, default='')),
                ('queue_size', models.PositiveIntegerField(default=0)),
                ('bridge_online', models.BooleanField(default=False)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='conference.meeting')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agent_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('summary', 'Summary'), ('todo', 'Todo'), ('decision', 'Decision'), ('code_task', 'Code Task'), ('reply', 'Reply')], max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('source_chunk_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='conference.meetingagentsession')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='conference.meeting')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='meetingagentsession',
            name='latest_result_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_sessions', to='conference.meetingartifact'),
        ),
        migrations.CreateModel(
            name='MeetingContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start_ms', models.PositiveIntegerField(default=0)),
                ('window_end_ms', models.PositiveIntegerField(default=0)),
                ('topic_label', models.CharField(blank=True, default='', max_length=120)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('todos', models.JSONField(blank=True, default=list)),
                ('source_chunk_ids', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_snapshots', to='conference.meeting')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingTranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_identity', models.CharField(blank=True, default='', max_length=120)),
                ('speaker_name', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(choices=[('live_stream', 'Live Stream'), ('manual', 'Manual'), ('mock', 'Mock')], default='manual', max_length=16)),
                ('text', models.TextField()),
                ('start_ms', models.PositiveIntegerField(default=0)),
                ('end_ms', models.PositiveIntegerField(default=0)),
                ('is_final', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('sequence_no', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='conference.meeting')),
            ],
            options={
                'ordering': ['sequence_no', 'created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingagentsession',
            constraint=models.UniqueConstraint(fields=('meeting', 'owner_user', 'agent_type'), name='uq_meeting_agent_session_owner_agent'),
        ),
    ]
