# Generated by Django 5.2.2 on 2026-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_meeting_realtime_bot_provider_and_volc_fields'),
        ('conference', '0019_meetingagentsession_meetingartifact_and_more'),
    ]

    operations = [
    ]
